/** @type {import('tailwindcss').Config} */
export default {
  content: ["./app/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#000000",
        "primary-container": "#1c1b1b",
        secondary: "#5f5e5c",
        "secondary-container": "#e1dfdc",
        tertiary: "#000000",
        "tertiary-container": "#1c1b1a",
        background: "#faf9f7",
        surface: "#faf9f7",
        "surface-dim": "#dadad8",
        "surface-bright": "#faf9f7",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3f1",
        "surface-container": "#efeeec",
        "surface-container-high": "#e9e8e6",
        "surface-container-highest": "#e3e2e0",
        "on-background": "#1a1c1b",
        "on-surface": "#1a1c1b",
        "on-surface-variant": "#444748",
        "on-primary-container": "#858383",
        "on-secondary-container": "#636360",
        "on-tertiary-container": "#868381",
        outline: "#747878",
        "outline-variant": "#c4c7c7",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "2xl": "48px",
        "3xl": "64px",
        gutter: "24px",
        "margin-page": "48px",
      },
      fontFamily: {
        serif: ["'Libre Caslon Text'", "serif"],
        sans: ["Geist", "sans-serif"],
        mono: ["Geist", "monospace"],
      },
    },
  },
  plugins: [],
}
